# Generated by Django 5.1.4 on 2024-12-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
